// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq_QPDdgSLApRb52uEViNQcSi-YBxeePM',
    appId: '1:508993839592:web:52d1ada2122ab2a659c45d',
    messagingSenderId: '508993839592',
    projectId: 'project-manager-489800',
    authDomain: 'project-manager-489800.firebaseapp.com',
    storageBucket: 'project-manager-489800.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYYYeNsLrYrtg-knlkUSGUvbzIpAV_w4g',
    appId: '1:508993839592:android:94786c5b8de423ac59c45d',
    messagingSenderId: '508993839592',
    projectId: 'project-manager-489800',
    storageBucket: 'project-manager-489800.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8HdRxFSjnGE_EJkvk-oEnfYKOlroUUfE',
    appId: '1:508993839592:ios:2526c55836800b5659c45d',
    messagingSenderId: '508993839592',
    projectId: 'project-manager-489800',
    storageBucket: 'project-manager-489800.firebasestorage.app',
    iosBundleId: 'com.project.gestion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8HdRxFSjnGE_EJkvk-oEnfYKOlroUUfE',
    appId: '1:508993839592:ios:55d006c1a38648f259c45d',
    messagingSenderId: '508993839592',
    projectId: 'project-manager-489800',
    storageBucket: 'project-manager-489800.firebasestorage.app',
    iosBundleId: 'com.example.projectManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq_QPDdgSLApRb52uEViNQcSi-YBxeePM',
    appId: '1:508993839592:web:6a911d0b7553efe759c45d',
    messagingSenderId: '508993839592',
    projectId: 'project-manager-489800',
    authDomain: 'project-manager-489800.firebaseapp.com',
    storageBucket: 'project-manager-489800.firebasestorage.app',
  );

}